image:
  repository: ghcr.io/utopian-contributors/upm-registry
  tag: latest
  pullPolicy: IfNotPresent

registry:
  port: 4873

api:
  port: 4000
  env:
    treasuryWalletSecret:
      name: solana-credentials
      key: TREASURY_WALLET_ADDRESS

sync:
  enabled: true

persistence:
  claimName: "upm-nfs-pvc"
  volumeName: "upm-nfs-pv"
  enabled: true
  storageClass: ""
  size: 10Gi

nfs:
  server: ""
  path: ""

ingress:
  enabled: true
  host: registry.utopian.build
  tls:
    enabled: true
    secretName: upm-tls

resources:
  registry:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 1Gi
  api:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  sync:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi
