{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
spec:
  storageClassName: ""           
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi              
  volumeName: {{ .Values.persistence.volumenName }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName }}
  labels:
    type: nfs-model-share
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: "" 
  mountOptions:
    - vers=4.1 # Remove this option to always use the latest version
    - hard # Retry I/O until server recovers
    - timeo=600 # RPC timeout (deciseconds)
    - retrans=2 # Retries before timing out
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
{{- end }}
